In [1]:
import pandas as pd
import numpy as np

In [2]:
df_order_item_refunds = pd.read_csv("../../MODULE 7 - Proje final/Toy store/order_item_refunds.csv")

In [3]:
df_item_refunds1 = df_order_item_refunds.copy()

In [4]:
df_item_refunds1.head()

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
0,1,2012-04-06 11:32:43,57,57,49.99
1,2,2012-04-13 01:09:43,74,74,49.99
2,3,2012-04-15 07:03:48,71,71,49.99
3,4,2012-04-17 20:00:37,118,118,49.99
4,5,2012-04-22 20:53:49,116,116,49.99

In [9]:
uplicate_orders  = df_item_refunds1[df_item_refunds1.duplicated(subset=['order_id'], keep=False)]

In [10]:
uplicate_orders

,order_item_refund_id,created_at,order_item_id,order_id,refund_amount_usd
487,488,2013-12-16 11:50:31,9407,9324,59.99
491,492,2013-12-19 21:50:31,9406,9324,49.99
1045,1046,2014-09-07 23:30:27,22767,19518,49.99
1104,1105,2014-09-13 02:30:27,22768,19518,59.99
1123,1124,2014-09-15 20:44:54,23227,19848,45.99
1179,1180,2014-09-22 10:44:54,23226,19848,49.99
1323,1324,2014-11-21 15:08:12,27964,23321,49.99
1337,1338,2014-11-28 18:08:12,27965,23321,45.99
1349,1350,2014-12-01 14:54:59,29530,24472,49.99
1398,1399,2014-12-10 22:54:59,29531,24472,29.99
1504,1505,2015-01-12 11:47:12,33000,27061,49.99
1525,1526,2015-01-19 13:47:12,33001,27061,45.99
1580,1581,2015-02-05 05:24:04,35360,28802,29.99
1602,1603,2015-02-12 06:24:04,35359,28802,49.99
1681,1682,2015-03-12 20:36:38,38896,31486,49.99
1699,1700,2015-03-17 17:36:38,38897,31486,45.99

In [18]:
# Convertir created_at en datetime
df_item_refunds1['created_at'] = pd.to_datetime(df_item_refunds1['created_at'])

# Conserver le dernier remboursement par order_id
df_item_refunds1_dedup = df_item_refunds1.sort_values('created_at').groupby('order_id', as_index=False).last()

In [19]:
uplicate_orders1  = df_item_refunds1_dedup[df_item_refunds1_dedup.duplicated(subset=['order_id'], keep=False)]

In [20]:
uplicate_orders1

Empty DataFrame
Columns: [order_id, order_item_refund_id, created_at, order_item_id, refund_amount_usd]
Index: []

In [21]:
# Exporter vers un nouveau fichier CSV
df_item_refunds1_dedup.to_csv('order_item_refunds_dedup.csv', index=False)